/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiV1RouteImport } from './routes/api.v1'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCreateWorkspaceRouteImport } from './routes/app.create-workspace'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppOrganizationsRouteImport } from './routes/app.organizations'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppReportRouteImport } from './routes/app.report'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppTimeRouteImport } from './routes/app.time'
import { Route as AppTriageRouteImport } from './routes/app.triage'
import { Route as InviteAcceptRouteImport } from './routes/invite.accept'
import { Route as ApiPlannerSplatRouteImport } from './routes/api.planner.$'
import { Route as ApiV1SplatRouteImport } from './routes/api.v1.$'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'
import { Route as AppOrganizationsIndexRouteImport } from './routes/app.organizations.index'
import { Route as AppOrganizationsOrgIdRouteImport } from './routes/app.organizations.$orgId'
import { Route as AppPlannerIndexRouteImport } from './routes/app.planner.index'
import { Route as AppPlannerPlanIdRouteImport } from './routes/app.planner.$planId'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'
import { Route as AppTicketsIndexRouteImport } from './routes/app.tickets.index'
import { Route as AppTicketsTicketIdRouteImport } from './routes/app.tickets.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Route = ApiV1RouteImport.update({
  id: '/api/v1',
  path: '/api/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateWorkspaceRoute = AppCreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeRoute = AppTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlannerSplatRoute = ApiPlannerSplatRouteImport.update({
  id: '/api/planner/$',
  path: '/api/planner/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiV1Route,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationsRoute,
} as any)
const AppOrganizationsOrgIdRoute = AppOrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AppOrganizationsRoute,
} as any)
const AppPlannerIndexRoute = AppPlannerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlannerRoute,
} as any)
const AppPlannerPlanIdRoute = AppPlannerPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => AppPlannerRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsTicketIdRoute = AppTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/app/create-workspace': typeof AppCreateWorkspaceRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/organizations': typeof AppOrganizationsRouteWithChildren
  '/app/planner': typeof AppPlannerRouteWithChildren
  '/app/report': typeof AppReportRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/time': typeof AppTimeRoute
  '/app/triage': typeof AppTriageRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/app/': typeof AppIndexRoute
  '/api/planner/$': typeof ApiPlannerSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/app/organizations/$orgId': typeof AppOrganizationsOrgIdRoute
  '/app/planner/$planId': typeof AppPlannerPlanIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/planner/': typeof AppPlannerIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/tickets/': typeof AppTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/app/create-workspace': typeof AppCreateWorkspaceRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/report': typeof AppReportRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/time': typeof AppTimeRoute
  '/app/triage': typeof AppTriageRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/app': typeof AppIndexRoute
  '/api/planner/$': typeof ApiPlannerSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/app/organizations/$orgId': typeof AppOrganizationsOrgIdRoute
  '/app/planner/$planId': typeof AppPlannerPlanIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/app/organizations': typeof AppOrganizationsIndexRoute
  '/app/planner': typeof AppPlannerIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/tickets': typeof AppTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/app/create-workspace': typeof AppCreateWorkspaceRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/organizations': typeof AppOrganizationsRouteWithChildren
  '/app/planner': typeof AppPlannerRouteWithChildren
  '/app/report': typeof AppReportRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/time': typeof AppTimeRoute
  '/app/triage': typeof AppTriageRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/app/': typeof AppIndexRoute
  '/api/planner/$': typeof ApiPlannerSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/app/organizations/$orgId': typeof AppOrganizationsOrgIdRoute
  '/app/planner/$planId': typeof AppPlannerPlanIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/planner/': typeof AppPlannerIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/tickets/': typeof AppTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/v1'
    | '/app/create-workspace'
    | '/app/inbox'
    | '/app/organizations'
    | '/app/planner'
    | '/app/report'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/time'
    | '/app/triage'
    | '/invite/accept'
    | '/app/'
    | '/api/planner/$'
    | '/api/v1/$'
    | '/api/webhooks/stripe'
    | '/app/organizations/$orgId'
    | '/app/planner/$planId'
    | '/app/projects/$projectId'
    | '/app/tickets/$ticketId'
    | '/app/organizations/'
    | '/app/planner/'
    | '/app/projects/'
    | '/app/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/v1'
    | '/app/create-workspace'
    | '/app/inbox'
    | '/app/report'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/time'
    | '/app/triage'
    | '/invite/accept'
    | '/app'
    | '/api/planner/$'
    | '/api/v1/$'
    | '/api/webhooks/stripe'
    | '/app/organizations/$orgId'
    | '/app/planner/$planId'
    | '/app/projects/$projectId'
    | '/app/tickets/$ticketId'
    | '/app/organizations'
    | '/app/planner'
    | '/app/projects'
    | '/app/tickets'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/v1'
    | '/app/create-workspace'
    | '/app/inbox'
    | '/app/organizations'
    | '/app/planner'
    | '/app/report'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/time'
    | '/app/triage'
    | '/invite/accept'
    | '/app/'
    | '/api/planner/$'
    | '/api/v1/$'
    | '/api/webhooks/stripe'
    | '/app/organizations/$orgId'
    | '/app/planner/$planId'
    | '/app/projects/$projectId'
    | '/app/tickets/$ticketId'
    | '/app/organizations/'
    | '/app/planner/'
    | '/app/projects/'
    | '/app/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiV1Route: typeof ApiV1RouteWithChildren
  InviteAcceptRoute: typeof InviteAcceptRoute
  ApiPlannerSplatRoute: typeof ApiPlannerSplatRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1': {
      id: '/api/v1'
      path: '/api/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create-workspace': {
      id: '/app/create-workspace'
      path: '/create-workspace'
      fullPath: '/app/create-workspace'
      preLoaderRoute: typeof AppCreateWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations': {
      id: '/app/organizations'
      path: '/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report': {
      id: '/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/time': {
      id: '/app/time'
      path: '/time'
      fullPath: '/app/time'
      preLoaderRoute: typeof AppTimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/triage': {
      id: '/app/triage'
      path: '/triage'
      fullPath: '/app/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planner/$': {
      id: '/api/planner/$'
      path: '/api/planner/$'
      fullPath: '/api/planner/$'
      preLoaderRoute: typeof ApiPlannerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof ApiV1Route
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/organizations/': {
      id: '/app/organizations/'
      path: '/'
      fullPath: '/app/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppOrganizationsRoute
    }
    '/app/organizations/$orgId': {
      id: '/app/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/app/organizations/$orgId'
      preLoaderRoute: typeof AppOrganizationsOrgIdRouteImport
      parentRoute: typeof AppOrganizationsRoute
    }
    '/app/planner/': {
      id: '/app/planner/'
      path: '/'
      fullPath: '/app/planner/'
      preLoaderRoute: typeof AppPlannerIndexRouteImport
      parentRoute: typeof AppPlannerRoute
    }
    '/app/planner/$planId': {
      id: '/app/planner/$planId'
      path: '/$planId'
      fullPath: '/app/planner/$planId'
      preLoaderRoute: typeof AppPlannerPlanIdRouteImport
      parentRoute: typeof AppPlannerRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets/': {
      id: '/app/tickets/'
      path: '/tickets'
      fullPath: '/app/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets/$ticketId': {
      id: '/app/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/app/tickets/$ticketId'
      preLoaderRoute: typeof AppTicketsTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppOrganizationsRouteChildren {
  AppOrganizationsOrgIdRoute: typeof AppOrganizationsOrgIdRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
}

const AppOrganizationsRouteChildren: AppOrganizationsRouteChildren = {
  AppOrganizationsOrgIdRoute: AppOrganizationsOrgIdRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
}

const AppOrganizationsRouteWithChildren =
  AppOrganizationsRoute._addFileChildren(AppOrganizationsRouteChildren)

interface AppPlannerRouteChildren {
  AppPlannerPlanIdRoute: typeof AppPlannerPlanIdRoute
  AppPlannerIndexRoute: typeof AppPlannerIndexRoute
}

const AppPlannerRouteChildren: AppPlannerRouteChildren = {
  AppPlannerPlanIdRoute: AppPlannerPlanIdRoute,
  AppPlannerIndexRoute: AppPlannerIndexRoute,
}

const AppPlannerRouteWithChildren = AppPlannerRoute._addFileChildren(
  AppPlannerRouteChildren,
)

interface AppRouteChildren {
  AppCreateWorkspaceRoute: typeof AppCreateWorkspaceRoute
  AppInboxRoute: typeof AppInboxRoute
  AppOrganizationsRoute: typeof AppOrganizationsRouteWithChildren
  AppPlannerRoute: typeof AppPlannerRouteWithChildren
  AppReportRoute: typeof AppReportRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTimeRoute: typeof AppTimeRoute
  AppTriageRoute: typeof AppTriageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppTicketsTicketIdRoute: typeof AppTicketsTicketIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateWorkspaceRoute: AppCreateWorkspaceRoute,
  AppInboxRoute: AppInboxRoute,
  AppOrganizationsRoute: AppOrganizationsRouteWithChildren,
  AppPlannerRoute: AppPlannerRouteWithChildren,
  AppReportRoute: AppReportRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTimeRoute: AppTimeRoute,
  AppTriageRoute: AppTriageRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppTicketsTicketIdRoute: AppTicketsTicketIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiV1RouteChildren {
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

const ApiV1RouteChildren: ApiV1RouteChildren = {
  ApiV1SplatRoute: ApiV1SplatRoute,
}

const ApiV1RouteWithChildren = ApiV1Route._addFileChildren(ApiV1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiV1Route: ApiV1RouteWithChildren,
  InviteAcceptRoute: InviteAcceptRoute,
  ApiPlannerSplatRoute: ApiPlannerSplatRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
